import { Dimensions } from 'react-native'
const {width, height} = Dimensions.get('screen')
const verdeO = '#206a5d'
const verde = '#80B314'
const cian = '#3ecc90'
const azul = '#4c73c2'
const rojo = '#c25a48'
const naranja = '#cc9e39'

const styles = {
    center: {
    flex: 15,
    alignSelf: 'stretch',
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginTop: 8,
    },
    subtitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: verdeO,
    },
    titleD: {
    fontSize: 14,
    fontWeight: 'bold',
    textAlign: 'center',
    paddingLeft: 10,
    color: naranja,
    },
    buttonD: {
    marginBottom: 5,
    padding: 5,
    paddingTop: 10,
    paddingBottom: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: verdeO,
    borderRadius: 20,
    width: width*0.8,
    height: width*0.15,
    },
    titleB: {
    fontSize: 12,
    fontWeight: 'bold',
    paddingLeft: 10,
    color: verdeO,
    },
    buttonB: {
    marginBottom: 5,
    marginRight: 20,
    padding: 5,
    paddingTop: 10,
    paddingBottom: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: verdeO,
    borderWidth: 2,
    borderRadius: 20,
    width: width*0.55,
    height: width*0.15,
    },
    item: {
    padding: 5,
    paddingTop: 10,
    width: width*0.7,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomWidth: 2,
    borderColor: verde,
    },
    textI: {
    fontSize: 14,
    fontWeight: 'bold',
    textAlign: 'center',
    color: verdeO,
    },
    FlatList: {
    alignSelf: 'stretch',
    },
    scroll: {
    alignSelf: 'stretch',
    },
    parraf: {
    paddingBottom: 8,
    paddingLeft: 20,
    paddingRight: 12,
    textAlign: 'justify',
    color: verdeO,
    },
    title: {
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    color: verdeO,
    paddingBottom: 10,
    },
    subtitle: {
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
    color: verdeO,
    marginHorizontal: 10,
    marginBottom: 10,
    },
    textA: {
    fontSize: 12,
    fontWeight: 'bold',
    textAlign: 'center',
    color: naranja,
    },
    textB: {
    fontSize: 12,
    fontWeight: 'bold',
    textAlign: 'center',
    color: verdeO,
    },
    textC: {
    marginLeft: 15,
    fontSize: 15,
    fontWeight: 'bold',
    color: verdeO,
    },
    textD: {
    fontSize: 14,
    fontWeight: 'bold',
    color: verdeO,
    marginHorizontal: 4,
    },
    space: {
    height: 15,
    },
    button: {
    backgroundColor: verde,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    width: width*0.8,
    borderRadius: 30,
    padding: 15,
    paddingHorizontal: 10,
    margin: 10,
    marginTop: 0,
    },
    button2: {
    margin: 10,
    height: 65,
    width: 250,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    padding: 5,
    backgroundColor: verdeO,
    },
    list: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
    height: 460,
    padding: 15,
    margin: 35,
    borderRadius: 20,
    },
    section: {
    width: width,
    paddingVertical: 10,
    },
    seccionFrame: {
    marginTop: 10,
    padding: 10,
    paddingHorizontal: 5,
    width: width*0.7,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: verdeO,
    borderRadius: 20,
    alignSelf: 'center',
    },
    mapImage: {
        resizeMode: 'cover',
        width: width,
        height: height*0.65,
        margin: 10,
        borderRadius: 20,
    },
    image: {
        width:width*0.8,
        height: width*0.4,
        alignSelf: 'center',
        resizeMode:'cover',
    },
    centro: {
    alignSelf: 'stretch',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
    marginBottom: 8,
    },
};

export default styles
